### ISSUE TITLE
Maps cannot be opened after saving them

### ISSUE THREAD

**Issue by Marmarter** [jeheydorn/nortantis#16] opened 2024-03-09 13:29 UTC
Error prompt:

Error while creating map: java.util.concurrent.ExecutionException: 
java.lang.NullPointerException: Cannot load from front array because "hsb" is null

**Comment by jeheydorn** [comment] 2024-03-09 15:50
That looks like [this issue](https://github.com/jeheydorn/nortantis/issues/14), which was fixed in version 1.1. Is it possible you're still using version 1.0? You can check the version in Help -> About Nortantis.

If you are on version 1.1 or later, then please send me your nort file so I can try to reproduce the issue. I think you should be able to attach it to this issue when you reply. Or if you'd rather not share it publicly, then you can send it to nortantis@gmail.com.

**Comment by jeheydorn** [comment] 2024-08-03 19:33
It's been a few months, so I'm closing this since I'm assuming you either found a solution it's no longer concern.

**Closed by jeheydorn** 2024-08-03 19:33 UTC
