### ISSUE TITLE
Issues and Ideas

### ISSUE THREAD

**Issue by Tr35n3r** [jeheydorn/nortantis#10] opened 2023-03-06 07:28 UTC
Hey there, thx for that amazing tool you made! I have a blast with it.

 - I created some .txt files that I added to the assets/books folder, but the program does not take them into account. It still takes names, locations etc. from the original .txt files even when I deselect them and take my own. Do i need to customize a file to have my own taken into account by the generator? If so, do I also have to assign which names are e.g. rivers and cities?
 - Any Idea when you finish the "road-work"?
 - A automaticly added scale (metric and imperial system) would be awesome or at least something to find out in which scale the map is, so I can create a scale myself.
 - I have noticed that when I manually change the colors of the regions in the generator, the program sometimes does not accept the colors I select, or colors another region that I have not selected.

**Comment by jeheydorn** [comment] 2023-03-06 13:22
You're the first person I've ever seen try to add their own book, so
congratulations on that :). To get the generator to use a new book on an
existing map, you need to go into the books tab and check it. If you don't
see the book there, that might mean there was a problem loading it. Also,
if your map has edits (created by launching the editor window), then the
text on the map is baked, so you'll either need to clear the edits, or go
into the editor, select the text tool, and manually delete and recreate
each text.

I had to pause the road project a couple years ago due to health problems.
I'm able to work on Nortantis again now, but I have some other stuff I want
to do before I get to the roads project, so it might be a while. My current
project is to combine the editor and generator settings into a single pane
of glass that displays the map with all features visible (as opposed to how
the current editor hides fancier stuff), and updates efficiently using
incremental drawing.

An automatically added scale would be a nice feature, but it's not
currently a priority for me. There isn't a concept of a physical size for
the maps as they are. Large bodies of land are created using one or more
tectonic plates, so I imagine a large body of land would be about the size
of Australia or North America, but some tectonic plates are smaller than
that, and mountains could form from tectonic activity smaller than entire
plates intersecting. The World size slider on the terrain panel determines
the number of polygons in the map, which roughly corresponds to how big the
world is.

I haven't seen the issue you're describing with region colors. What does
the editor do when it rejects the color you selected? Does it initially
paint the color and then later forget it? If so, what step did you take
when it forgot the color? If you could send me a series of steps to
consistently reproduce the problem, that would be great.

**Comment by jeheydorn** [comment] 2023-03-06 13:31
Another question with the issue with region colors - how many region colors
were on the map (approximately)? I found a bug a few days ago that might
cause the behavior you're seeing if the number of region colors exceeded
256.

**Comment by Tr35n3r** [comment] 2023-03-06 14:57
1. Seriously? Cool :D I see my book in the book list, so far everything fits. It just doesn't apply these names onto the map. The editor takes names from other books, although I have selected ONLY my own. I even tried to adjust the .properties File of my map, but it didn't help. When working on the .properties file i saw, that there is a "t" in front of the Books Names. I tried to put this "t" in front of my book name as well, it still always takes others. so there must be an issue somewhere that my book is displayed in the selection, but not transferred to the map.
2. Nice, sound great. Looking forward to this :)
3. Great would be, if adjusting borders would be easyer and not tied to "paint region"
4. I will try do some thinking and let you know if I find something useful to use as scale. Maybe you can use it too
5. It does nothing special, it colors... like it supose to to, but not always the region I want. Yes it has forgot a color, the color white (a pure white) for example. The other things are that I wanted to change a regions color, but it changed another region into a color I didn't choose or I clicked on "Select color from map" and it took a complet different color. Is the mail address on your website nortantis@gmail.com still in use? I could send you some screenshots

**Comment by jeheydorn** [comment] 2023-03-06 15:44
Regard 1, Nortantis uses the books you select to generate new names that
sound similar to the names from the books; it won't actually use the names
directly from the books (except it uses noun-adjective and noun verb-pairs
to name rivers and mountains). Maybe that's a point of confusion here. If
you want to use the names from your books, you'll have to use the editor to
edit the text manually.

Regarding 5, yes, that email address is still in use. If you want to also
send the properties file, it might be helpful.

**Comment by Tr35n3r** [comment] 2023-03-07 09:52
A Mail was sent :)

**Comment by jeheydorn** [comment] 2023-12-25 22:26
I'm closing this issue since the issue with region colors was fixed a while back.

**Closed by jeheydorn** 2023-12-25 22:26 UTC
