### ISSUE TITLE
New Problem

### ISSUE THREAD

**Issue by MalachiteDrake** [jeheydorn/nortantis#4] opened 2019-01-17 10:01 UTC
I downloaded the new version, but now I can't get it to open. I don't see the files that were in the last download for running it in Windows. I tried running it from the command prompt, but nothing happened. I'm not sure what to do now?

**Comment by jeheydorn** [comment] 2019-01-18 03:11
I don't know what could have happened. I downloaded the zip file, extracted
it, and ran the generator with no trouble.

**Comment by MalachiteDrake** [comment] 2019-01-18 07:58
Yup, I just downloaded something wrong. I did it again and got it working,
but it still only exports if the resolution is set to .25, but now the map
comes out...weird? Everything's smudged across the land formations so you
can't tell what's what. I've tried all different settings on the program,
but every time this is the map I get.

[image: image.png]

Thanks again for all the work you've done on this!

**Comment by jeheydorn** [comment] 2019-01-19 13:34
Your screenshot does not seem to have attached.

The first question to answer is whether this problem was caused by the settings file you have, or by the generator downloaded. Try going to File - New to create a new settings file, and see if that one generates correctly.

**Comment by MalachiteDrake** [comment] 2019-01-20 07:14
I tried that, but it still came out wrong. Hopefully it attached this time.

**Comment by jeheydorn** [comment] 2019-01-22 03:01
I've never tried to attach an image in a github issue, so I don't know how or if it works. But I still don't see your attachment. Try sending it to nortantis@gmail.com.

**Comment by jeheydorn** [comment] 2019-04-12 11:27
I'm closing this because we resolved it by email some time back. MalachiteDrake was exporting to heightmap instead of generating a regular map.

**Closed by jeheydorn** 2019-04-12 11:27 UTC
